### ISSUE TITLE
Could OSZ theoretically fit on a floppy, maybe 2.88 MB fat one ?

### ISSUE THREAD

**Issue by informer2016** [bztsrc/osz#1]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

I've noticed OS/Z live images are 8 MB. Are they already compressed, or maybe there is still room for compression? _(allowing to compress it further, maybe to 2.88 MB if 1.44 MB is impossible)_

**Comment by bztsrc** [comment]
Hi informer2016!

Floppies are not supported by OS/Z, not even virtual ones. I use SD cards and USB sticks for removable media for over two decades, I suggest for you to do the same.

OS/Z can already be part of a BIOS build by using BBS compatible ROM images. The loader is in one ROM, and if the initrd is not found on storage (or network, nor received over serial etc. see the [BOOTBOOT specification](https://github.com/bztsrc/bootboot/blob/master/bootboot_spec_1st_ed.pdf)), as a last resort it is looked up in ROM. This way you can have an up-to-date, fully-featured initrd on a flashcard for example, and a fallback, fail-safe version in ROM in case of any boot failure. For initrd compression currently GZIP implemented (on all supported platforms), but it's straightforward to add LZMA compression to the loader.

The current compressed initrd is about a few hundred kilobytes, and when it's fully implemented, it won't exceed 1M, never ever. The only reason of 8Mb image is stupid firmware implementations and mkfs tools which refuse to create and read smaller fat images. The loader itself does not care about the size (or the number of clusters), and it also does not care about partition alignment either. So it will work fine if you create a non-standard fat16 image with the smallest possible cluster table (but don't expect any standard filesystem driver or tool to read that fs image or any real hardware to boot from it). Should work on BIOS machines though (which luckily does not know or care about filesystems).

Alternatively you can skip fat fs alltogether, and put the initrd file's content on a partition as-is (using the appropriate partition type uuid of course). But again, since real hardware (UEFI and RPi, but not BIOS) demands a boot partition with fat I would not recommend that if you ever want to boot your image on a real machine.

Happy new year, btw!

**Comment by informer2016** [comment]
@bztsrc Hi Zoltan, thank you very much for such detailed answer, now I see it is possible. Wish you a great 2018 year of the Yellow Earth Dog: happy life to you and bugless code :smile: :dog2:

**Comment by bztsrc** [comment]
Thanks, but spare me and leave that dog thing for the masses, as a scientist I prefer common-sense. Horoscopes did not send people to space, science did.
